# Generated by Django 5.2.9 on 2026-04-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuemodel',
            name='last_name',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
