# Generated by Django 6.0 on 2026-01-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuesmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
