# Generated by Django 5.2.9 on 2026-04-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venuemodel_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuemodel',
            name='last_name',
        ),
    ]
