# Generated by Django 5.2.9 on 2026-04-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_remove_venuemodel_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuemodel',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='venue_pics/'),
        ),
    ]
