# Generated by Django 5.2.9 on 2026-04-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_venuemodel_venue_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venuemodel',
            old_name='venue_image',
            new_name='image',
        ),
    ]
