# Generated by Django 5.2.9 on 2026-04-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_rename_venue_image_venuemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuemodel',
            name='image',
            field=models.ImageField(blank=True, default='venue_pics/default.png', null=True, upload_to='venue_pics/'),
        ),
    ]
