# Generated by Django 5.2.9 on 2026-04-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_alter_venuemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuemodel',
            name='display_label',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
