# Generated by Django 5.2.9 on 2026-04-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_venuemodel_display_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuemodel',
            name='display_label',
            field=models.CharField(default='', max_length=100),
        ),
    ]
