# Generated by Django 5.2.9 on 2026-04-18 15:08

import django.db.models.deletion
import django.utils.timezone
import seasons.models
import seasons.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_type', models.CharField(default='In Person', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default=0)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=seasons.utils.ThreeMonthsLater)),
                ('season_type', models.ForeignKey(default=seasons.models.SeasonTypeModel.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='seasons.seasontypemodel')),
            ],
        ),
    ]
