# Generated by Django 5.2.9 on 2026-02-02 16:12

import django.db.models.deletion
import seasons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_seasontypemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonmodel',
            name='season_type',
            field=models.ForeignKey(default=seasons.models.SeasonTypeModel.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='seasons.seasontypemodel'),
        ),
    ]
