# Generated by Django 5.2.9 on 2026-04-18 15:08

import datetime
import django.db.models.deletion
import django.utils.timezone
import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('players', '__first__'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(default=0)),
                ('prize', models.FloatField(default=0)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='players.playermodel')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Tournament Name', max_length=100, unique=True)),
                ('total_prize_pool', models.FloatField(default=0)),
                ('time', models.TimeField(default=datetime.time(10, 0))),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('override_message', models.TextField(blank=True, default='', null=True)),
                ('finalized', models.BooleanField(default=False)),
                ('game_type', models.ForeignKey(default=games.models.GameTypeModel.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='games.gametypemodel')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='venues.venuemodel')),
                ('winners', models.ManyToManyField(to='tournaments.winnersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentPlayersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('registration_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='players.playermodel')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tournaments.tournamentmodel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tournament', 'player'), name='tournament_unique_registration')],
            },
        ),
    ]
