# Generated by Django 5.2.9 on 2026-04-08 14:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(default=0)),
                ('prize', models.FloatField(default=0)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='players.playermodel')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Tournament Name', max_length=100, unique=True)),
                ('total_prize_pool', models.FloatField(default=0)),
                ('date', models.DateField(default=datetime.datetime(2026, 4, 8, 14, 39, 29, 234449, tzinfo=datetime.timezone.utc))),
                ('override_message', models.TextField(default='', null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='venues.venuemodel')),
                ('winners', models.ManyToManyField(to='tournaments.winnersmodel')),
            ],
        ),
    ]
