# Generated by Django 5.2.9 on 2026-04-08 16:02

import datetime
import django.db.models.deletion
import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_rename_canceledgames_canceledgamesmodel'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='game_type',
            field=models.ForeignKey(default=games.models.GameTypeModel.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='games.gametypemodel'),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 8, 16, 2, 51, 927631, tzinfo=datetime.timezone.utc)),
        ),
    ]
