# Generated by Django 5.2.9 on 2026-04-08 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournamentmodel_game_type_alter_tournamentmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 8, 22, 30, 16, 93962, tzinfo=datetime.timezone.utc)),
        ),
    ]
