# Generated by Django 5.2.9 on 2026-04-08 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournamentmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 8, 23, 21, 57, 858611, tzinfo=datetime.timezone.utc)),
        ),
    ]
