# Generated by Django 5.2.9 on 2026-04-08 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournamentmodel_finalized_alter_tournamentmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 8, 23, 42, 15, 143562, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='override_message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
