# Generated by Django 6.0.2 on 2026-04-09 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournamentmodel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 9, 23, 56, 41, 682976, tzinfo=datetime.timezone.utc)),
        ),
    ]
