# Generated by Django 5.2.9 on 2026-04-11 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournamentmodel_time_alter_tournamentmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 11, 14, 17, 13, 368539, tzinfo=datetime.timezone.utc)),
        ),
    ]
