# Generated by Django 5.2.9 on 2026-04-11 14:21

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('tournaments', '0007_alter_tournamentmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 11, 14, 21, 45, 193578, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='TournamentPlayersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('registration_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='players.playermodel')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tournaments.tournamentmodel')),
            ],
        ),
    ]
