# Generated by Django 5.2.9 on 2026-04-11 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('tournaments', '0008_alter_tournamentmodel_date_tournamentplayersmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 11, 14, 22, 41, 66540, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddConstraint(
            model_name='tournamentplayersmodel',
            constraint=models.UniqueConstraint(fields=('tournament', 'player'), name='tournament_unique_registration'),
        ),
    ]
