# Generated by Django 5.2.9 on 2026-04-16 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_alter_tournamentmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 16, 15, 35, 56, 581834, tzinfo=datetime.timezone.utc)),
        ),
    ]
