# Generated by Django 5.2.9 on 2026-04-16 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_alter_tournamentmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
