# Generated by Django 5.2.9 on 2026-04-18 15:08

import django.db.models.deletion
import django.utils.timezone
import players.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('players', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('registration_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='games.playedgamemodel')),
                ('player', models.ForeignKey(default=players.models.PlayerModel.get_default_pk, on_delete=django.db.models.deletion.PROTECT, related_name='PlayerResult', to='players.playermodel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'player'), name='unique_registration')],
            },
        ),
    ]
