# Generated by Django 5.2.9 on 2026-02-02 15:46

import django.db.models.deletion
import players.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameresults', '0001_initial'),
        ('games', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresultmodel',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='games.playedgamemodel'),
        ),
        migrations.AddField(
            model_name='gameresultmodel',
            name='player',
            field=models.ForeignKey(default=players.models.PlayerModel.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='players.playermodel'),
        ),
        migrations.AddConstraint(
            model_name='gameresultmodel',
            constraint=models.UniqueConstraint(fields=('game', 'player'), name='unique_registration'),
        ),
    ]
