# Generated by Django 6.0.2 on 2026-03-20 03:54

import django.db.models.deletion
import players.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameresults', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresultmodel',
            name='player',
            field=models.ForeignKey(default=players.models.PlayerModel.get_default_pk, on_delete=django.db.models.deletion.PROTECT, related_name='PlayerResult', to='players.playermodel'),
        ),
    ]
