# Generated by Django 6.0.2 on 2026-03-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameresults', '0002_alter_gameresultmodel_player'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gameresultmodel',
            name='unique_registration',
        ),
    ]
