# Generated by Django 6.0.2 on 2026-02-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameresults', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresultmodel',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
