# Generated by Django 6.0.2 on 2026-03-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameresults', '0003_remove_gameresultmodel_unique_registration'),
        ('games', '0004_canceledgames'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gameresultmodel',
            constraint=models.UniqueConstraint(fields=('game', 'player'), name='unique_registration'),
        ),
    ]
