# Generated by Django 5.2.9 on 2026-04-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
