# Generated by Django 5.2.9 on 2026-04-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_api', '0002_usermodel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='file',
        ),
    ]
