# Generated by Django 5.2.9 on 2026-04-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_api', '0003_remove_usermodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
    ]
