# Generated by Django 5.2.9 on 2026-04-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_api', '0006_alter_usermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
