# Generated by Django 5.2.9 on 2026-04-16 23:20

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_api', '0007_alter_usermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US'),
        ),
    ]
