# Generated by Django 5.2.9 on 2026-04-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_api', '0008_usermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
