# Generated by Django 5.2.9 on 2026-04-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_api', '0009_alter_usermodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='display_name',
            field=models.CharField(default='Mr. No Name', max_length=50),
            preserve_default=False,
        ),
    ]
