# Generated by Django 5.2.9 on 2025-12-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageText',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('color', models.CharField(default='#0000DD', max_length=10)),
                ('font_size', models.IntegerField(default=18)),
            ],
        ),
    ]
