# Generated by Django 5.2.9 on 2026-04-18 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageText',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('color', models.CharField(default='#0000DD', max_length=10)),
                ('font_size', models.IntegerField(default=18)),
                ('order', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialMessages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('color', models.CharField(default='#0000DD', max_length=10)),
                ('font_size', models.IntegerField(default=18)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
