# Generated by Django 5.2.9 on 2025-12-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagetext',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
