# Generated by Django 6.0 on 2025-12-26 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Data', '0002_homepagetext_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialMessages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('color', models.CharField(default='#0000DD', max_length=10)),
                ('font_size', models.IntegerField(default=18)),
                ('date', models.DateField(default=datetime.date(2025, 12, 26))),
            ],
        ),
    ]
