# Generated by Django 5.2.9 on 2026-01-09 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Data', '0004_alter_specialmessages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialmessages',
            name='date',
            field=models.DateField(default=datetime.date(2026, 1, 9)),
        ),
    ]
