# Generated by Django 6.0 on 2026-01-16 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Data', '0010_alter_specialmessages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialmessages',
            name='date',
            field=models.DateField(default=datetime.date(2026, 1, 16)),
        ),
    ]
