# Generated by Django 6.0 on 2026-01-21 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Data', '0016_alter_specialmessages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialmessages',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 21, 18, 6, 42, 525527, tzinfo=datetime.timezone.utc)),
        ),
    ]
