# Generated by Django 6.0 on 2026-01-21 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Data', '0017_alter_specialmessages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialmessages',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
