# Generated by Django 5.2.9 on 2026-02-02 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestingGameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestingSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestingSectionThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learning.testinggamemodel')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learning.testingsectionmodel')),
            ],
        ),
        migrations.AddField(
            model_name='testinggamemodel',
            name='all_sections',
            field=models.ManyToManyField(related_name='game_sections', through='learning.TestingSectionThrough', to='learning.testingsectionmodel'),
        ),
    ]
