# Generated by Django 6.0 on 2026-01-18 22:20

import datetime
import django.db.models.deletion
import games.models
import players.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_alter_playermodel_player'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.CharField(default=0)),
                ('start_date', models.DateField(default=datetime.date(2026, 1, 18))),
            ],
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='venues.venuemodel')),
            ],
        ),
        migrations.CreateModel(
            name='GameResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=-1)),
                ('registration_date_time', models.DateTimeField(default=datetime.datetime(2026, 1, 18, 22, 20, 13, 214164, tzinfo=datetime.timezone.utc))),
                ('player', models.ForeignKey(default=players.models.PlayerModel.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='players.playermodel')),
            ],
        ),
        migrations.CreateModel(
            name='PlayedGameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2026, 1, 18))),
                ('player_results', models.ManyToManyField(to='games.gameresultmodel')),
                ('which_game', models.ForeignKey(default=games.models.GameModel.get_default_pk, on_delete=django.db.models.deletion.PROTECT, related_name='game_details', to='games.gamemodel')),
            ],
        ),
    ]
