# Generated by Django 5.2.9 on 2026-02-12 00:10

import django.db.models.deletion
import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Texas Holdem', max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='game_type',
            field=models.ForeignKey(default=games.models.GameTypeModel.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='games.gametypemodel'),
        ),
    ]
