# Generated by Django 6.0 on 2026-02-01 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='venues.venuemodel'),
        ),
        migrations.AddField(
            model_name='sectionthrough',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectionthrough',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.gamemodel'),
        ),
        migrations.AddField(
            model_name='sectionthrough',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.sectionmodel'),
        ),
        migrations.AddField(
            model_name='playedgamemodel',
            name='which_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='played_games', to='games.sectionthrough'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='all_sections',
            field=models.ManyToManyField(related_name='game_sections', through='games.SectionThrough', to='games.sectionmodel'),
        ),
    ]
