# Generated by Django 5.2.9 on 2026-01-09 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('venues', '0002_venuesmodel_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesmodel',
            name='Venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='venues.venuesmodel'),
        ),
    ]
