# Generated by Django 6.0 on 2026-01-18 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresultmodel',
            name='registration_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 18, 22, 20, 31, 801721, tzinfo=datetime.timezone.utc)),
        ),
    ]
