# Generated by Django 6.0 on 2026-01-16 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedgamemodel',
            name='date',
            field=models.DateField(default=datetime.date(2026, 1, 16)),
        ),
        migrations.AlterField(
            model_name='seasonmodel',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 1, 16)),
        ),
    ]
