# Generated by Django 6.0 on 2026-01-18 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresultmodel',
            name='registration_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 18, 17, 58, 48, 470777, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='playedgamemodel',
            name='date',
            field=models.DateField(default=datetime.date(2026, 1, 18)),
        ),
        migrations.AlterField(
            model_name='seasonmodel',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 1, 18)),
        ),
    ]
