# Generated by Django 5.2.9 on 2026-04-20 14:52

import django.db.models.deletion
import seasons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='season_type',
            field=models.ForeignKey(default=seasons.models.SeasonTypeModel.get_default_pk, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='seasons.seasontypemodel'),
        ),
    ]
