# Generated by Django 5.2.9 on 2026-01-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamesmodel_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesmodel',
            name='Text',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
