# Generated by Django 6.0.2 on 2026-03-19 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gametypemodel_gamemodel_game_type'),
        ('seasons', '0003_seasonmodel_season_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedgamemodel',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='playedgame_season', to='seasons.seasonmodel'),
        ),
    ]
