# Generated by Django 6.0 on 2026-01-16 21:09

import datetime
import django.db.models.deletion
import players.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_playedgamemodel_date_and_more'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playedgamemodel',
            name='players',
        ),
        migrations.CreateModel(
            name='GameResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=-1)),
                ('registration_date_time', models.DateTimeField(default=datetime.datetime(2026, 1, 16, 13, 9, 45, 209851))),
                ('player', models.ForeignKey(default=players.models.PlayerModel.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='players.playermodel')),
            ],
        ),
        migrations.AddField(
            model_name='playedgamemodel',
            name='player_results',
            field=models.ManyToManyField(to='games.gameresultmodel'),
        ),
    ]
