# Generated by Django 5.2.9 on 2026-01-18 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gameresultmodel_registration_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresultmodel',
            name='registration_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 18, 20, 32, 10, 819342, tzinfo=datetime.timezone.utc)),
        ),
    ]
