# Generated by Django 5.2.9 on 2026-04-20 16:40

import django.db.models.deletion
import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gamemodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='game_type',
            field=models.ForeignKey(default=games.models.GameTypeModel.get_default_pk, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='games.gametypemodel'),
        ),
    ]
