# Generated by Django 6.0 on 2026-02-03 21:35

import django.db.models.deletion
import seasons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
        ('seasons', '0003_seasonmodel_season_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='season_type',
            field=models.ForeignKey(default=seasons.models.SeasonTypeModel.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='seasons.seasontypemodel'),
        ),
    ]
