# Generated by Django 6.0 on 2026-01-16 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_playedgamemodel_players_gameresultmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresultmodel',
            name='registration_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 16, 21, 25, 16, 957757, tzinfo=datetime.timezone.utc)),
        ),
    ]
