# Generated by Django 6.0 on 2026-02-04 01:27

import django.db.models.deletion
import seasons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamemodel_season_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionthrough',
            name='section',
            field=models.ForeignKey(default=seasons.models.SeasonTypeModel.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='games.sectionmodel'),
        ),
    ]
