# Generated by Django 5.2.9 on 2026-01-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamesmodel_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesmodel',
            name='Text',
        ),
        migrations.AddField(
            model_name='gamesmodel',
            name='Description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='gamesmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
