# Generated by Django 6.0 on 2026-01-20 17:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_gameresultmodel_registration_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(default='Texas Holdem', max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gameresultmodel',
            name='registration_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 20, 17, 28, 22, 895536, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='playedgamemodel',
            name='date',
            field=models.DateField(default=datetime.date(2026, 1, 20)),
        ),
        migrations.AlterField(
            model_name='seasonmodel',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 1, 20)),
        ),
        migrations.CreateModel(
            name='EventThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.eventmodel')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.gamemodel')),
            ],
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='all_events',
            field=models.ManyToManyField(related_name='events', through='games.EventThrough', to='games.eventmodel'),
        ),
    ]
