# Generated by Django 6.0.2 on 2026-03-27 14:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_playedgamemodel_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanceledGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('which_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canceled_games', to='games.gamemodel')),
            ],
        ),
    ]
