# Generated by Django 6.0 on 2026-01-20 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_eventmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresultmodel',
            name='registration_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 20, 23, 49, 18, 300393, tzinfo=datetime.timezone.utc)),
        ),
    ]
