# Generated by Django 6.0.2 on 2026-03-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_canceledgames'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CanceledGames',
            new_name='CanceledGamesModel',
        ),
    ]
