# Generated by Django 6.0 on 2026-01-16 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_gameresultmodel_registration_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresultmodel',
            name='registration_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 16, 21, 27, 32, 241695, tzinfo=datetime.timezone.utc)),
        ),
    ]
