# Generated by Django 6.0 on 2026-02-04 01:29

import django.db.models.deletion
import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_sectionthrough_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionthrough',
            name='section',
            field=models.ForeignKey(default=games.models.SectionModel.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='games.sectionmodel'),
        ),
    ]
