# Generated by Django 6.0 on 2026-01-10 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_gamesmodel_text_gamesmodel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayedGamesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date(2026, 1, 10))),
                ('Season', models.IntegerField(default=0)),
            ],
        ),
    ]
