# Generated by Django 6.0 on 2026-01-10 19:16

import django.db.models.deletion
import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_playedgamesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedgamesmodel',
            name='WhichGame',
            field=models.ForeignKey(default=games.models.GamesModel.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='games.gamesmodel'),
        ),
    ]
