# Generated by Django 6.0 on 2026-01-20 23:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_gameresultmodel_registration_date_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='event',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='active',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='director',
        ),
        migrations.AddField(
            model_name='eventthrough',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventthrough',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameresultmodel',
            name='registration_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 20, 23, 49, 32, 155414, tzinfo=datetime.timezone.utc)),
        ),
    ]
