# Generated by Django 6.0 on 2026-01-21 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_rename_event_eventmodel_name_remove_gamemodel_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresultmodel',
            name='registration_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 1, 2, 23, 943497, tzinfo=datetime.timezone.utc)),
        ),
    ]
