# Generated by Django 6.0 on 2026-01-10 19:17

import players.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_playedgamesmodel_whichgame'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedgamesmodel',
            name='Players',
            field=models.ManyToManyField(default=players.models.PlayersModel.get_default_pk, to='players.playersmodel'),
        ),
    ]
