# Generated by Django 6.0 on 2026-01-11 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_playedgamesmodel_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedgamesmodel',
            name='Date',
            field=models.DateField(default=datetime.date(2026, 1, 11)),
        ),
    ]
