# Generated by Django 6.0 on 2026-01-21 01:03

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_gameresultmodel_registration_date_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventModel',
            new_name='SectionModel',
        ),
        migrations.RenameModel(
            old_name='EventThrough',
            new_name='SectionThrough',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='all_events',
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='all_sections',
            field=models.ManyToManyField(related_name='game_sections', through='games.SectionThrough', to='games.sectionmodel'),
        ),
        migrations.AlterField(
            model_name='gameresultmodel',
            name='registration_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 1, 3, 9, 434086, tzinfo=datetime.timezone.utc)),
        ),
    ]
