# Generated by Django 6.0 on 2026-01-21 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_rename_eventmodel_sectionmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='description',
        ),
        migrations.AlterField(
            model_name='gameresultmodel',
            name='registration_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 1, 8, 30, 79225, tzinfo=datetime.timezone.utc)),
        ),
    ]
