# Generated by Django 6.0 on 2026-01-11 20:09

import datetime
import django.db.models.deletion
import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_playedgamesmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeansonNumber', models.IntegerField(default=0)),
                ('StartDate', models.DateField(default=datetime.date(2026, 1, 11))),
            ],
        ),
        migrations.AlterField(
            model_name='playedgamesmodel',
            name='WhichGame',
            field=models.ForeignKey(default=games.models.GamesModel.get_default_pk, on_delete=django.db.models.deletion.PROTECT, related_name='game_details', to='games.gamesmodel'),
        ),
    ]
