# Generated by Django 6.0 on 2026-01-12 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_seasons_alter_playedgamesmodel_whichgame'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seasons',
            new_name='SeasonsModel',
        ),
    ]
