# Generated by Django 6.0 on 2026-01-21 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_remove_gamemodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionthrough',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='gameresultmodel',
            name='registration_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 1, 8, 49, 747931, tzinfo=datetime.timezone.utc)),
        ),
    ]
