# Generated by Django 5.2.9 on 2026-01-21 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_sectionthrough_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresultmodel',
            name='registration_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 4, 34, 52, 582415, tzinfo=datetime.timezone.utc)),
        ),
    ]
