# Generated by Django 6.0 on 2026-01-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_rename_seasons_seasonsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonsmodel',
            name='SeansonNumber',
        ),
        migrations.AddField(
            model_name='seasonsmodel',
            name='SeasonNumber',
            field=models.CharField(default=0),
        ),
    ]
