# Generated by Django 5.2.9 on 2026-01-21 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_gameresultmodel_registration_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresultmodel',
            name='registration_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 4, 43, 11, 982530, tzinfo=datetime.timezone.utc)),
        ),
    ]
