# Generated by Django 6.0 on 2026-01-12 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_remove_seasonsmodel_seansonnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playedgamesmodel',
            name='Season',
        ),
    ]
