# Generated by Django 6.0 on 2026-01-14 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_remove_playedgamesmodel_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedgamesmodel',
            name='Date',
            field=models.DateField(default=datetime.date(2026, 1, 13)),
        ),
        migrations.AlterField(
            model_name='seasonsmodel',
            name='StartDate',
            field=models.DateField(default=datetime.date(2026, 1, 13)),
        ),
    ]
