# Generated by Django 6.0 on 2026-01-14 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_alter_playedgamesmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedgamesmodel',
            name='Date',
            field=models.DateField(default=datetime.date(2026, 1, 14)),
        ),
        migrations.AlterField(
            model_name='seasonsmodel',
            name='StartDate',
            field=models.DateField(default=datetime.date(2026, 1, 14)),
        ),
    ]
