# Generated by Django 6.0 on 2026-01-21 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_gamemodel_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionthrough',
            old_name='event',
            new_name='section',
        ),
        migrations.AlterField(
            model_name='gameresultmodel',
            name='registration_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 18, 3, 30, 718249, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='playedgamemodel',
            name='date',
            field=models.DateField(default=datetime.date(2026, 1, 21)),
        ),
        migrations.AlterField(
            model_name='seasonmodel',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 1, 21)),
        ),
    ]
