# Generated by Django 6.0 on 2026-01-21 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_rename_event_sectionthrough_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresultmodel',
            name='registration_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 18, 6, 42, 540841, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='playedgamemodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 21, 18, 6, 42, 552841, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='seasonmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 21, 18, 6, 42, 538679, tzinfo=datetime.timezone.utc)),
        ),
    ]
