# Generated by Django 6.0 on 2026-01-21 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_alter_gameresultmodel_registration_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresultmodel',
            name='registration_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='playedgamemodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='seasonmodel',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
