# Generated by Django 6.0 on 2026-01-22 16:48

import django.db.models.deletion
import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_gamemodel_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedgamemodel',
            name='which_game',
            field=models.ForeignKey(default=games.models.GameModel.get_default_pk, on_delete=django.db.models.deletion.PROTECT, related_name='played_games', to='games.sectionthrough'),
        ),
    ]
