# Generated by Django 6.0 on 2026-01-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_alter_playedgamemodel_which_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedgamemodel',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
