# Generated by Django 6.0 on 2026-01-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_playedgamemodel_finalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionthrough',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
