# Generated by Django 6.0 on 2026-01-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_alter_sectionthrough_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
