# Generated by Django 5.2.9 on 2026-01-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_remove_playedgamemodel_player_results_and_more'),
        ('players', '0003_playermodel_first_name_playermodel_last_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gameresultmodel',
            constraint=models.UniqueConstraint(fields=('game', 'player'), name='unique_registration'),
        ),
    ]
