# Generated by Django 6.0 on 2026-01-30 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_gameresultmodel_unique_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresultmodel',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playedgamemodel',
            name='which_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='played_games', to='games.sectionthrough'),
        ),
    ]
