# Generated by Django 6.0 on 2026-01-31 05:33

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_alter_gameresultmodel_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonmodel',
            name='end_date',
            field=models.DateField(default=games.models.ThreeMonthsLater),
        ),
    ]
