# Generated by Django 6.0 on 2026-01-31 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_seasonmodel_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonmodel',
            old_name='season_number',
            new_name='season',
        ),
    ]
