# Generated by Django 5.2.9 on 2026-04-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(default='', unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='', null=True)),
                ('first_name', models.CharField(blank=True, default='', null=True)),
                ('last_name', models.CharField(blank=True, default='', null=True)),
                ('password', models.CharField(blank=True, default='', null=True)),
                ('test', models.CharField(blank=True, default='', null=True)),
            ],
        ),
    ]
