# Generated by Django 6.0 on 2026-01-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersmodel',
            name='phone',
            field=models.CharField(default=''),
        ),
    ]
