# Generated by Django 6.0 on 2026-01-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='player',
            field=models.CharField(default='', unique=True),
        ),
    ]
