# Generated by Django 6.0 on 2026-01-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_playersmodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersmodel',
            name='phone',
            field=models.CharField(default='', null=True),
        ),
    ]
