# Generated by Django 5.2.9 on 2026-04-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_playermodel_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='test',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
