# Generated by Django 6.0 on 2026-01-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_playermodel_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='first_name',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='last_name',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='password',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
