# Generated by Django 6.0 on 2026-01-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_playersmodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='playersmodel',
            name='phone',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
