# Generated by Django 5.2.9 on 2026-04-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_playermodel_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermodel',
            name='test',
        ),
    ]
