# Generated by Django 5.2.9 on 2026-04-23 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_remove_playermodel_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='winners_pics/default.jpg', upload_to='winners_pics')),
                ('display_text', models.CharField(max_length=100, null=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winning_player', to='players.playermodel')),
            ],
        ),
    ]
